apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 34
    namespace 'expo.modules.wearosconnector'

    defaultConfig {
        minSdkVersion 24
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation 'com.google.android.gms:play-services-wearable:18.1.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
